### ISSUE TITLE
Requested Code Change

### ISSUE THREAD

**Issue by delashum** [QuickbaseAdmirer/QuickBase-PHP-SDK#3]
Just a small thing, but on line 417 there is function edit_record. If this function is used to upload a file to a record but not change any other fields there is an error.

The following change should be made.
- Line 417; "$fields" to "$fields = 0"
- Wrap the proceeding "foreach($fields...) { ... }" in "if ($fields) { ...}".

Tested with no errors. Thanks for this awesome SDK!

**Comment by litan1106** [comment]
This SDK is outdated for the current API 
http://www.quickbase.com/api-guide/index.html#intro.html

**Comment by penawebservices** [comment]
@litan1106, so I shouldn't use this code? Is there an updated package? Thanks!

**Comment by funkymonk91** [comment]
You can use it, @litan1106's api is just newer. The SDK works just fine still.

**Comment by tflanagan** [comment]
This SDK "works" fine, but is very out dated. It doesn't have every API call available nor every option, ie user tokens.

I've developed a "future-proof" api that has all these missing features and is actively maintained.

https://github.com/tflanagan/php-quickbase

`composer require tflanagan/quickbase`
